general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita abrir múltiplas instâncias do hyprlock
    before_sleep_cmd = loginctl lock-session    # Bloqueia a tela antes do PC suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Religa a tela ao acordar
}

# (Opcional) Configuração para desligar a tela após X minutos de inatividade
listener {
    timeout = 300                                 # 5 minutos
    on-timeout = loginctl lock-session            # Aciona o bloqueio
}
