-- Generated by nwg-displays on 2026-08-23 at 18:38:06. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@59.99",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1366x0",
    scale = 1.1999999999999993
})
